/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_highfly029_GameNativeLibrary */

#ifndef _Included_com_highfly029_GameNativeLibrary
#define _Included_com_highfly029_GameNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    setPrint
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_highfly029_GameNativeLibrary_setPrint
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    loadNavMesh
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_highfly029_GameNativeLibrary_loadNavMesh
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    findPathStraight
 * Signature: (ILjava/lang/String;FFFFFF)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_highfly029_GameNativeLibrary_findPathStraight
  (JNIEnv *, jobject, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    raycast
 * Signature: (ILjava/lang/String;FFFFFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_highfly029_GameNativeLibrary_raycast
  (JNIEnv *, jobject, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    release
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_highfly029_GameNativeLibrary_release
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    addObstacle
 * Signature: (ILjava/lang/String;FFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_highfly029_GameNativeLibrary_addObstacle
  (JNIEnv *, jobject, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    addBoxObstacle
 * Signature: (ILjava/lang/String;FFFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_highfly029_GameNativeLibrary_addBoxObstacle__ILjava_lang_String_2FFFFFF
  (JNIEnv *, jobject, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    addBoxObstacle
 * Signature: (ILjava/lang/String;FFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_com_highfly029_GameNativeLibrary_addBoxObstacle__ILjava_lang_String_2FFFFFFF
  (JNIEnv *, jobject, jint, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    removeOneObstacle
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_highfly029_GameNativeLibrary_removeOneObstacle
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    removeAllObstacle
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_highfly029_GameNativeLibrary_removeAllObstacle
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    update
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_highfly029_GameNativeLibrary_update
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
