/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_highfly029_GameNativeLibrary */

#ifndef _Included_com_highfly029_GameNativeLibrary
#define _Included_com_highfly029_GameNativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_highfly029_GameNativeLibrary
 * Method:    testJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_highfly029_GameNativeLibrary_testJni
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
